### ISSUE TITLE
Safe operator/expression objects

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#15]
*Originally reported by* **Pieter Collins (Bitbucket: [pietercollins](https://bitbucket.org/pietercollins), GitHub: [pietercollins](https://github.com/pietercollins))**

----------------------------------------

The current way of handling operators and symbolic expressions is not type-safe and is sensitive to bugs. Need a more type-safe solution.

One possibility would be to use a *variant* object, but std::variant is not yet available and boost::variant is less powerful and more buggy. A more lightweight alternative would be to use Operator types with restricted Code enumerations.

----------------------------------------
- Bitbucket: https://bitbucket.org/ariadne-cps/development/issue/15

**Comment by lgeretti** [comment]
Has this been already addressed @pietercollins ?

**Comment by pietercollins** [comment]
Used internal CodedVariant for operators, and std::variant for Symbolic expressions. 
Some clean-up of symbolic functionality still needed; see issue #281
