### ISSUE TITLE
Merge Figure and HybridFigure functionality?

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#206]
I noticed that the HybridFigure functionality seems not really tied to hybrid objects, in the sense that it should be possible to write a Figure class that can be extended to the hybrid case with very small changes, instead of having all the code repeated. Also, HybridFigure has some symbolic functionality that Figure would benefit from.

Am I wrong @pietercollins ? Would this be feasible?

**Comment by pietercollins** [comment]
It is probably feasible to merge this. I think the main difference is that our "Hybrid" sets typically have variable names associated, wheras Euclidean ones don't.

**Comment by pietercollins** [comment]
For now, the Set and HybridSet classes might be *just* sufficiently different to require a different front-end Figure class.

**Comment by lgeretti** [comment]
What about using variable names for the non-hybrid case though? That would be a nice addition and it would make the interface consistent, even though we have two different classes.

**Comment by pietercollins** [comment]
I want to keep the main kernel based on indexed variables (Vector) for efficiency. However, the `Valuation`, `Expression` and `ExpressionSet` classes provide named variables. In principle, they can replace `Vector`, `Function` and `Set`.

**Comment by lgeretti** [comment]
I don't understand: why avoid using named variables if the kernel includes the symbolic module? Also, some symbolic manipulation is sometimes necessary (e.g., checking if a function is constant or additive in some variables, for differential inclusion function manipulation purposes). Shouldn't we just use named variables at the user layer, and indexed variables internally? I guess this choice does not affect efficiency significantly, while it offers a consistent user experience across continuous and hybrid systems.

**Comment by pietercollins** [comment]
We do allow for named variables at the user layer, *except* that the Solver classes work with `Function` not `Expression`. We could (and at some point probably should) wrap the Solver classes. We will then also need to provide more conversions from numbered to named variables.

**Comment by lgeretti** [comment]
The DI integrator will be an extension of Integrator, and it does require a symbolic representation of the function for exact manipulation purposes. So I am essentially forced to provide a symbolic interface. This also suggests that, for consistency, an extension/wrapper of the other integrators that simply provides a symbolic interface should be offered. Do you agree?

**Comment by lgeretti** [comment]
Not to be worked on.
