### ISSUE TITLE
Allow VectorFieldEvolver to plot results versus time

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#222]
Timed evolution cannot be currently plotted in the continuous case, due to the different way we handle graphics and enclosures in the hybrid case.

**Comment by lgeretti** [comment]
(this is one of the deficiencies that release-1.0 had and that continuous evolution in the development version still has)

**Comment by pietercollins** [comment]
Suggest addressing this by providing a `graph(Function) -> Curve` method, so we can generate a plottable set.
