### ISSUE TITLE
Make Writer/Format classes for output streaming

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#239]
We shall provide Format classes in order to format a class for output streaming.

**Comment by pietercollins** [comment]
I've added a templated Writer(Interface) class  for formatted output, and provided an implementation for Dyadic.

**Comment by pietercollins** [comment]
Approach is approved; implement for other classes, especially number and function classes.

**Comment by lgeretti** [comment]
Moved assignment to me. Will work on some select classes for numbers, functions and automata: essentially everything that often shows up (in a ugly way) in the logs.

**Comment by lgeretti** [comment]
Done everything relevant for now, will proceed as soon as required to apply this approach to other classes
