### ISSUE TITLE
Step size as Dyadic is not particularly readable on the standard output

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#254]
After the changes that exposed the step size as Dyadic, understanding its printed value is not that easy anymore.

For example, a step size equal to 0.1 shows as `3602879701896397/2^55`. I hope you agree @pietercollins that for visualization purposes this is not ideal.

**Comment by lgeretti** [comment]
Depends on #239

**Comment by pietercollins** [comment]
This has been addressed by the `Dyadic` `Writer` classes.
