### ISSUE TITLE
series_flow_step failing on DI examples

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#286]
I tried plugging the series_flow_step function in place of the Picard method within the DI integrator. Unfortunately, the examples (any in examples/noisy) return the following:

```c++
terminate called after throwing an instance of 'std::runtime_error'
  what():  std::runtime_error in function/scaled_function_patch.hpp:903: partial_evaluate: Assertion `decide(contains(tf.domain()[k],c))' failed.
```

I did not make a test right now since any noisy example would do, but I did create a `working-solvers-series_flow_step#286` branch with the plugging in of the flow function. Could you check this @pietercollins ?

**Comment by pietercollins** [comment]
I'll take a look at this, but need to work on other things more urgently...

**Comment by lgeretti** [comment]
Ok, it would be great though if we could get this function to work by the end of the weekend, so that I can update the results for the paper (due by the end of Monday).

Again, if you need to test the behavior, you can try examples/noisy/harmonic-oscillator. It fails at the first step, whatever the approximation. You can change examples/noisy/noisy-utilities.hpp from lines 116 to 137 so to modify the verbosity and the approximation method used, if relevant to testing.

**Comment by pietercollins** [comment]
OK, I'll make it highest priority tomorrow morning.

**Comment by lgeretti** [comment]
I noticed that series_flow_step assumes that the time domain is not centered around the current time, i.e. `[-h,h]` but it is rather `[-h+t,t+h]`. In particular it assumes that we supply `[t,t+h]` as input.

This is quite different from how the Picard case works and it also affects the construction of the `w`s accordingly. Therefore I tried running the harmonic oscillator in the ZERO case for simplicity, where w is not present, and supplying the [0,h] interval which is correct for the first step. It progressed after calculating the flow set, but then it stopped with:

`harmonic-oscillator(14934,0x11b5525c0) malloc: *** error for object 0x2: pointer being freed was not allocated`

**Comment by pietercollins** [comment]
I'

**Comment by lgeretti** [comment]
I pushed an update to working-solvers-series_flow_step#286 that should fix errors for the DI integrator, though what I get is divergence of the evolve set. I am also working on the VectorFieldEvolver by plugging the series_flow_step. There I noticed an extra problem: if our step size requires a very accurate representation (e.g., `0.02` becomes `5764607523034235/2^58`) then the construction of the time bounds in series_flow_step fails, since the lower bound can't be represented exactly in FloatDP.

**Comment by pietercollins** [comment]
The correct StepSizeType is problematic. I think it's ok to use a Dyadic or Float, since the step size is a computational artifact which we control. This means that 0.02 will never be the step size since it's not an exact dyadic.
There are two realistic choices for StepSizeType. The first is Dyadic (the current type) and the second is FloatDPValue (the type used as the endpoints of a function model domain).
- The advantage of FloatDPValue is that we can then always use it as an endpoint of the time domain of the flow.
- The main advantage of Dyadic is that it supports exact arithmetic. We can therefore always compute t+h for a step size h. Additionally, we can use arbitrarily short steps.

After using Dyadic for the StepSizeType, I'm beginning to think that FloatDPValue might be better. 

The main difficulty is that we generally want t, h, t+h, and t-h all to be exactly representable. Note that if t>0 and t+h are exactly representable, and h<=t, then h and t-h are exactly representable. but in the (rare) cases that h>t, this is not the case. This is because our flow code requires t to be the exact centre of [t-h,t+h]. However, we run into this problem as well if we take a Dyadic StepSizeType.

**Comment by lgeretti** [comment]
Can we use Dyadic and just lift the restriction of converting exactly when computing the time bounds (and when getting the evolve set), and rather use the lower bound of the conversion?

**Comment by pietercollins** [comment]
That will work (for the user interface).

**Comment by pietercollins** [comment]
Are you working on the failing test_continuous_evolution and test_reachability_analyser or should I?

**Comment by lgeretti** [comment]
I wouldn't look into test_reachability_analyser if I were you: test_continuous_evolution should suffice. Both fail because of my change to VectorFieldEvolver to use series_flow_step. These are just temporary hacks to try and understand why series_flow_step causes a significant overapproximation of the evolve set.

Anyway, if you could look into that problem it would be great.

**Comment by pietercollins** [comment]
The problem is that series_flow_step returns a function on interval [t,t+h], whereas integrator->flow_step returns interval [0,h].

**Comment by pietercollins** [comment]
I'll augment the Integrator class to provide a flow_step for parametrised autonomous systems dx/dt=f(x,a), and parametrised time-dependent systems dx/dt=f(x,t,a)

**Comment by lgeretti** [comment]
Ok, my bad, indeed I missed the partial evaluate on the right value of the time. Could you please also look into the best way to convert the Dyadic bounds for series_flow_step?

**Comment by pietercollins** [comment]
I've added extensions to the Bounder functionality, clearly separating the cases with explicit time-dependence and with parameters.
I've added a flow_step for parametrised flows to the TaylorSeriesIntegrator, which simply calls the series_flow_step function.

**Comment by pietercollins** [comment]
I hope that these additions are enough for today as I have to work on something else now.

**Comment by lgeretti** [comment]
It is a bit unwieldy to have the time-invariant version assuming a time domain centered on 0, while the time-variant version assuming it centered on t. Apart from that, VectorField evolution seems to work correctly. 

Notably, the new flow_step method is a lot slower on the same configuration as the old one. When using series_flow_step directly I used order 8, while the default TaylorSeriesIntegrator uses 12.

**Comment by pietercollins** [comment]
We could make the time-invariant version start at a time other than 0. We could even compute the flow over an interval [t_l, t_u] with phi(x,t_0)=x for some t_0 in [t_l,t_u] not necessarily the initial point. Feel free to make suggestions.
The old method should be faster as it uses a custom data structure. I would like to translate the new method to this approach sometime soon.

**Comment by lgeretti** [comment]
I don't have a strong preference. The important thing is that we have consistent behaviors among the different integrators, so for generality I think we should integrate around t in all cases.

It's good that we can use get a performance boost on the integrator.

By the way: I just fixed the DI integrator, the problem being that the reach set was incorrectly projecting time onto t-h instead of t. So right now the DI integrator has been modified to comply to TaylorSeriesIntegrator, but that prevents me from using the Picard scheme. This is an inconvenience for plugging the preferred integrator.

**Comment by lgeretti** [comment]
Quick evaluation: I tried some of the examples and it seems that we get a very slight improvement for the zero, constant and piecewise approximations. The affine and sinusoidal instead return a very bad result. 

Here I need a bit of help since I am uncertain about the effect of changing the time domain on the w functions. For example, if in the affine case we originally had the term (t-h/2)/h for domt=[0,h], does the term change for domt=[t,t+h] ?

**Comment by lgeretti** [comment]
I rebased working-series_flow_step#105 and applied the commits you added to the branch for this issue. 

I will keep a separate subbranch for my changes to use the new TaylorSeriesIntegrator, but until the difference in handling the time domain is addressed, I'd rather not merge anything of mine.

**Comment by lgeretti** [comment]
I'm closing this and creating separate issues for the problems-at-hand.
