### ISSUE TITLE
Determinant of a Matrix and singular matrices

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#290]
Is there a particular reason why we do not provide the determinant function for a Matrix @pietercollins ?

And secondarily, if I wanted just to identify if the Matrix is singular, what is the fastest way in the library at the moment?

**Comment by pietercollins** [comment]
The textbook computation of determinant by cofactor expansion is inefficient above the 3×3 case; it is better to compute the LU factorisation, and take the product of the diagonal entries of U. However, this may fail for interval matrices or if the matrix is (nearly) singular if the pivoting cannot be resolved. For these reasons it's not particularly clear what the best implementation of determinant should be in the near-singular case.

Currently, the inverse(A) method for FloatDPBounds throws a SingularMatrixException if lu_inverse throws a DIvideByZeroException; however, this behaviour has not been tested, and you may just end up with inf's and NaN's. 
Alternatively you could try to compute the LU factorisation (triangular_decomposition); if the matrix is nonsingular, all should go well, and U will have nonzero diagonal entries.

**Comment by lgeretti** [comment]
Ok thanks. I was just interested in identifying singularity, so computing the inverse would be sufficient, though I am concerned about the efficiency of that approach.

**Comment by pietercollins** [comment]
Do you want to check for singularity or non-singularity? 
The latter case is more usual; here it suffices to compute the LU-factorisation with sufficiently high precision. If the computation fails, you are singular, or at least very close.
In the former case, you (in principle) need to use Rational/ExactNumber coefficients.

For Validated (interval) matrices, the situation is more complicated...

**Comment by lgeretti** [comment]
Well, non-singularity would be sufficient, since it is needed for approximate SQP optimization.

**Comment by pietercollins** [comment]
It's probably best to try the computation as see if anything goes wrong (either an exception or inf/NaN's)
