### ISSUE TITLE
Graded pow() not implemented

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#297]
I am getting a 

```c++
Not implemented: Ariadne::Graded<A> Ariadne::pow(const Ariadne::Graded<A>&, Ariadne::Int) [with A = Ariadne::Differential<Ariadne::Bounds<Ariadne::FloatDP> >; Ariadne::Int = int]
``` 

when using `GradedTaylorSeriesIntegrator`. Since many of the DI systems that we run rely on powers, this functionality should definitely be put in.

**Comment by pietercollins** [comment]
I've been working on this, but the code is nontrivial and will take some more thinking about.
