### ISSUE TITLE
HybridReachabilityAnalyser and algebraic equations

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#301]
The HybridReachabilityAnalyser does not account correctly for algebraic equations in the dynamics. This in turn raises an error for which a variable is not found in the state space of certain locations.

**Comment by pietercollins** [comment]
Setting one algebraic variable as a function of another algebraic variable gives an error due to failing to find that variable in the state variables.

**Comment by pietercollins** [comment]
Fixed issue when an algebraic variable occurs in the defining equation of another in `CompositeHybridAutomaton`.
