### ISSUE TITLE
Introduce the ability to compute the series expansion of a flow without the remainder term

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#314]
In order to support the ability to compute the remainder from an initial box, we should provide the ability to compute an approximate flow expansion up to a given order.

**Comment by pietercollins** [comment]
We should do this by introducing an ApproximateIntegrator class which returns an ApproximateFunctionModel as the flow.

**Comment by lgeretti** [comment]
Duplicate of #325
