### ISSUE TITLE
Add Taylor models with interval coefficients

### ISSUE THREAD

**Issue by pietercollins** [ariadne-cps/ariadne#319]
Add Taylor models with interval coefficients (and remainder). This will allow us to reimplement the Flow* algorithms.

**Comment by pietercollins** [comment]
An issue with the interval Taylor models (and approximate Taylor models) is testing. The existing tests sometimes check the exact representations. Do we want to replicated this approach, where appropriate, for interval Taylor models?

**Comment by lgeretti** [comment]
I think this should be replicated, where appropriate clearly.

**Comment by pietercollins** [comment]
Added interval-based Taylor models and functions.
Since these are multivalued functions, they do not conform to the `FunctionInterface`.

Many changes were needed to get the instantiations to compile; the major cleanup of the function model classes is needed; see #334
