### ISSUE TITLE
MissingGuardException on invariants

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#330]
It seems that the latest changes made to catch open systems broke the correct identification of invariants: for example, both examples/hybrid/watertank/watertank-hysteresis.cpp and tutorials/hybrid_evolution/hybrid_evolution_tutorial.cpp, while perfectly fine, give an error that disappears if the guard(s) are removed. In the first case, the error is:

```
terminating with uncaught exception of type Ariadne::MissingGuardError: MissingGuardError in CompositeHybridAutomaton::mode(DiscreteLocation): Automaton has location (controller|rising,valve|opened) with event ?<??
```

and similarly for the second case.

**Comment by pietercollins** [comment]
Fixed. Error was due to checking event kinds (which include 'invariant's) against resets, as opposed to guards against resets.
