### ISSUE TITLE
CMake fails on ariadne-master.zip

### ISSUE THREAD

**Issue by pietercollins** [ariadne-cps/ariadne#349]
I tried building from the GitHub generated zip file `ariadne-master.zip`, but this failed with the output below. The first problem seems to be incorrect handling of pybind11. Note that building from a clean clone of the repository succeeded.

> mkdir build; cd build; cmake ..

-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cotire 1.8.0 loaded.
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen dot 
-- Found DOXYFILE_IN: /home/collins/Source/ariadne-master/doc/Doxyfile.in  
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of char
-- Check size of char - done
-- Check size of short int
-- Check size of short int - done
-- Check size of int
-- Check size of int - done
-- Check size of long int
-- Check size of long int - done
-- Check size of long long int
-- Check size of long long int - done
-- Check size of float
-- Check size of float - done
-- Check size of double
-- Check size of double - done
-- Check size of long double
-- Check size of long double - done
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for execinfo.h
-- Looking for execinfo.h - found
-- Looking for C++ include cxxabi.h
-- Looking for C++ include cxxabi.h - found
-- Found GMP: /usr/include/x86_64-linux-gnu (Required is at least version "5.1.0") 
-- Found GMPXX: /usr/lib/x86_64-linux-gnu/libgmpxx.so  
-- Found MPFR: /usr/include (Required is at least version "1.0.0") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'cairo'
--   Found cairo, version 1.15.10
-- Found Cairo: /usr/lib/x86_64-linux-gnu/libcairo.so  
-- Found GTK2_GTK: /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so  
-- CXX target ariadne-numeric cotired.
-- CXX target ariadne-algebra cotired.
-- CXX target ariadne-function cotired.
-- CXX target ariadne-solvers cotired.
-- CXX target ariadne-geometry cotired.
-- CXX target ariadne-dynamics cotired.
-- CXX target ariadne-symbolic cotired.
-- cotire disabled for the output module due to conflicts with the GTK2 library.
-- CXX target ariadne-hybrid cotired.
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.8") 
-- PythonLibs found: Python bindings will be built.
-- pybind11 dependency not available.
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Downloading it...
-- Downloaded pybind11 dependency successfully.
CMake Error at CMakeLists.txt:130 (add_subdirectory):
  The source directory

    /home/collins/Source/ariadne-master/external/pybind11

  does not contain a CMakeLists.txt file.

-- You will have to use the Python  interpreter to import Ariadne correctly.
-- CXX target pyariadne-numeric-submodule-obj cotired without precompiled header. Too few applicable sources.
-- CXX target pyariadne-algebra-submodule-obj cotired.
-- CXX target pyariadne-extra-submodule-obj cotired.
CMake Error at python/CMakeLists.txt:34 (string):
  string sub-command STRIP requires two arguments.

CMake Error at python/CMakeLists.txt:35 (install):
  install TARGETS given no LIBRARY DESTINATION for module target "pyariadne".

-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.8") 
-- pytest package found, Python tests will be performed.
-- Configuring incomplete, errors occurred!
See also "/home/collins/Source/ariadne-master/build/CMakeFiles/CMakeOutput.log".

**Comment by lgeretti** [comment]
The problem is due to the fact that the zip file does not have the .git subdirectory required for submodules. The solution is to check whether there exists a .git directory: if not, then
1) "git init"
2) remove the external/pybind11 directory (required to add the submodule manually)
3) run the proper "git submodule add" command
and now it will be possible to "git submodule update --init" correctly.

Will do that as soon as possible. After the fix we will also need to drop a new master release, necessarily.

**Comment by lgeretti** [comment]
Resolved on 1037003d
