### ISSUE TITLE
Clean-up Evolver/Enclosure Configuration

### ISSUE THREAD

**Issue by pietercollins** [ariadne-cps/ariadne#351]
We should clean-up the Evolver and Enclosure configurations. 
- We should definitely have Evolver classes have an associated EnclosureConfiguration, rather than just creating an EnclosureConfiguration from a FunctionModelFactory and a default Paver/Drawer.
- Should we refactor the EvolverConfiguration classes so that all related Solver classes are in the configuration? e.g. Should VectorFieldEvolverConfiguration have an Integrator and an EnclosureConfiguration, or should these be entirely separate?
-  Should we rename EnclosureConfiguration to EnclosureProperties? Pro: Enclosures have data, and we've been using Properties for e.g. Number classes. Con: The Configuration details algorithms only, not properties of the data. 
    - Propose using an EnclosureFactory rather than an EnclosureConfiguration in Evolvers
    - Should we also give FunctionSet objects a Configuration?

**Comment by lgeretti** [comment]
I agree on the first point. 

Regarding the second point, it seems a good idea to keep everything together.

On the renaming, I don't have a strong preference, and I don't see any concept that fits into a single word. Properties seems fine. On the Con you mention, I don't think that we really need to distinguish. On the two subpoints you mention, do what you feel is more consistent given the above changes.

**Comment by lgeretti** [comment]
Changed evolver class interface quite a bit from that time, closing this.
