### ISSUE TITLE
Remove AtomicHybridAutomaton

### ISSUE THREAD

**Issue by pietercollins** [ariadne-cps/ariadne#356]
The `AtomicHybridAutomaton` class is a simple wrapper around `HybridAutomaton` which requires that all locations have a single discrete variable, which is named after the automaton itself. 

Since the  extra functionality is limited (syntactic sugar), one of the two classes can be dropped. We should definitely keep the `HybridAutomaton` class, since it is closed under composition (i.e. the `CompositeHybridAutomaton` class can be flattened to a `HybridAutomaton`).

**Comment by lgeretti** [comment]
Removed, along with cif_automaton.hpp that derived from it, as of ae4efb52
