### ISSUE TITLE
Plot of reachable set fails for algebraic-differential systems

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#366]
If you try the tutorial in the hybrid-plot-algebraic#366 branch, it will fail during plotting with:

``
terminating with uncaught exception of type std::runtime_error: std::runtime_error in /Users/lgeretti/Public/sources/ariadne-cps/ariadne/source/symbolic/space.cpp:119: Ariadne::SizeType Ariadne::Space<Ariadne::Real>::index(const typename Space<T>::VariableType &) const [T = Ariadne::Real]: Assertion `false' failed.
  Variable aperture is not in the Space [height]
``

We are clearly not handling algebraic variables properly here.

**Comment by lgeretti** [comment]
Depends on #370

**Comment by pietercollins** [comment]
Added `Storage` classes for paved reachable sets with adjoined auxiliary variables.
