### ISSUE TITLE
Crossing issues

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#37]
Using the test_crossings_issue in the *crossings-issue* branch, if we use a step size of 1e-2, we get:

```
#!c++

[:0] Unexpected error in computing critical time for event comes:
  std::runtime_error in /Users/lgeretti/Public/sources/ariadne-all/ariadne/geometry/enclosure.cc:492: : Assertion `time.argument_size()==this->number_of_parameters()' failed.
```

If on the other hand we use a step size of 1e-3, for example, we get a segfault.

**Comment by lgeretti** [comment]
Depends on #93

**Comment by pietercollins** [comment]
Two separate issues are still present:
a) Sometimes the discrete transition is not triggered.
b) Sometimes the continuous evolution does not proceed even when it should.

**Comment by lgeretti** [comment]
The continuous evolution not proceeding has been solved. The spurious progress is not an error per se, and can be solved by changing the step size.
