### ISSUE TITLE
Add named variables and auxiliary functions to dynamic systems, Orbits and GridTreePaving

### ISSUE THREAD

**Issue by pietercollins** [ariadne-cps/ariadne#370]
We should have a uniform interface for systems and their behaviour. In particular, all systems  should use named variables and allow auxiliary equations (currently `Map` does not), and the `Orbit` classes should have information about auxiliary variables. Further, `HybridGridTreePaving` could be given information about auxiliary variables, or else we need a new class e.g. `HybridGridTreePavingEnclosure` to contain this.

**Comment by lgeretti** [comment]
Will this include the ability of VectorField to plot versus the TimeVariable?

**Comment by pietercollins** [comment]
We should be able to plot the behaviour of a continuous-time system agains time (after these changes).

**Comment by pietercollins** [comment]
I see two main mays of accomplishing this. Either we provide a flag in an `Evolver` or `Analyser` object determining whether auxiliary variables are output or not (the latter should be more efficient). Or we append auxiliary variable information (possibly not computed explicitly, but just supply the auxiliary function) in the `Enclosure`/`Orbit` classes. 
I'm not sure what's best. Any ideas, @lgeretti ?

**Comment by lgeretti** [comment]
Enclosure already has the auxiliary mapping, Orbit doesn't need to because it reads it from the enclosures stored within. On the contrary, GridPaving lacks this information and that's the issue.
I would enrich GridPaving with the auxiliary mapping in order to allow proper plotting also for those. It seems the shortest path and it is consistent with what we already did.

**Comment by pietercollins** [comment]
The reason for not augmenting `GridPaving` directly is that it is a "pure set" class, so just represents the Euclidean state set. We should provide a new augmented class, just as `Enclosure` is an augmented `ConstrainedImageSet`.

**Comment by lgeretti** [comment]
I am ok with a (Hybrid)PavingEnclosure (I believe we can and should abstract everything apart the fact that, compared to an Enclosure, this is a paving).

Although in this case there is less use since, compared with Enclosure, we can't carry timing or event trace information along.

**Comment by pietercollins** [comment]
Added named variables and auxiliary functions to `Map` and `VectorField`.

**Comment by pietercollins** [comment]
Added `Storage` class to keep track of global sets in dynamic systems, analogous to `Enclosure`.

**Comment by pietercollins** [comment]
Trying to keep separation between Euclidean state sets (used directly in computation) and sets with (auxiliary mappings and) named variables. Adding `LabelledEnclosure` and `LabelledStorage` to keep track of names.

**Comment by pietercollins** [comment]
Planning (a) class(es) containing extra system information on auxiliary map and named variables. This will keep this information from overly-cluttering constructors.

**Comment by pietercollins** [comment]
Adding `LabelledFigure` and `LabelledDrawableInterface` for plotting named sets.
I tried adapting `Figure` to accept either labelled or Euclidean objects, but this doesn't fit nicely with our strong typing of other objects.
However, this requires some knock-on changes, including a specialisation of `ListSet<LabelledEnclosure>` (or `LabelledListSet<Enclosure>`), and making sure that all figures either take Euclidean or labelled objects. It will take some effort to do this without extra code bloat.

**Comment by pietercollins** [comment]
Completed new functionality. Clean-up urgently needed; see #387.
