### ISSUE TITLE
Rely on sorted variables in HybridAutomaton

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#375]
After fixing issue #374 I noticed that there are still some uses of unsorted auxiliary variables within the HybridAutomaton implementation. I did some (overly due) tests with multiple algebraic variables in one mode and it seems that everything works now. For all practical purposes though I believe that auxiliary variables should be always exposed as sorted, since auxiliary functions have a codomain relying on sorted auxiliary variables. Otherwise, it might get confusing. This renders the auxiliary field in DiscreteMode redundant.

Also, the list of variables in CompositeHybridAutomaton remains a simple join of the variables in all components. But this is currently not a problem since the space function is constructed from this list.

Summarizing, @pietercollins shall we resort on sorted variables throughout? In other terms, shouldn't we expose a list of variables that is invariant on the ordering of the components when creating a ComposedHybridAutomaton?

**Comment by pietercollins** [comment]
It's certainly the case that we should always expose variables in the same order.

For now, I think it's find that the order should be the sorted order. But we could also try to maintain the declaration order; this would require some (fairly minor, I think) changes to make_auxiliary_function, and might be more intuitive.

Longer-term, it might be best to try and expose less through the Function interface, and keep more as Expression objects.
Even with sorted variables, the ordering of variables _does_ depend on the ordering of components in a composition.

**Comment by lgeretti** [comment]
> Even with sorted variables, the ordering of variables does depend on the ordering of components in a composition

How so? Can't we just do the same as we are doing with algebraic variables and keep the state variables sorted mode by mode?

Luca

**Comment by pietercollins** [comment]
Changed the auxiliary mapping to not require variables to be sorted. So we just keep the variables in _declared_ order throughout.
