### ISSUE TITLE
Construct a ContinuousPredicate from a conjunction/disjunction of predicates

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#377]
If I try the following:
```
RealVariable x("x");
ContinuousPredicate guard(x<=2 and x>=0);
```

I get the errors:
```
error: no viable conversion from 'VariableUpperInterval<Ariadne::Real>' to 'bool'
    ContinuousPredicate guard(x<=2 and x>=0);
                              ^~~~~~~~~
/Users/lgeretti/Public/sources/ariadne-cps/ariadne/source/solvers/../symbolic/expression_set.hpp:150:5: note: candidate function
    operator VariableInterval<UB>() const { return VariableInterval<UB>(-infinity,_variable,_upper); }
    ^
/Users/lgeretti/Public/sources/ariadne-cps/ariadne/source/solvers/../symbolic/expression_set.hpp:153:5: note: candidate function
    operator Expression<Kleenean>() const {
    ^
error: invalid operands to binary expression ('VariableUpperInterval<Ariadne::Real>' and
      'VariableLowerInterval<Ariadne::Real>')
    ContinuousPredicate guard(x<=2 and x>=0);
                              ~~~~~~~~~ ^   ~~~~~~~~~
```

It seems the conjunction is only possible if I do it from two previously-constructed ContinuousPredicate objects.
This is not particularly pretty from a system definition viewpoint, since we would like to construct invariants and guards directly without explicit intermediate objects.

Is it possible to fix this @pietercollins ?

**Comment by pietercollins** [comment]
This shouldn't be too hard; my guess is inheriting `VariableUpper/LowerInterval` from `DeclareExpressionOperations<Kleenean> `should work, though we may also have to define the appropriate conversions.

We currently use `a <= x <= b` to define a `VariableInterval` which is used to define `VariablesBox`. This could also be seen as a shorthand for the `ContinuousPredicate` representing `a<=x and x<=b`, but I think that it's better to force users to write the latter explicitly, so not convert `VariableInterval` to `ContinuousPredicate`.

**Comment by lgeretti** [comment]
I agree we don't need to support the conversion from `VariableInterval`, also considering that it is a special (albeit not so rare) case.

**Comment by lgeretti** [comment]
Ok, I tried it and it works syntactically. However, numerically there are issues computing the Lie derivative. I'll make another issue.
