### ISSUE TITLE
Inconsistent use of an equality symbol for initial point/set

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#383]
For the simulator, which accepts a HybridPoint as input, if we wanted to set the `x` variable to 1 we would use the `x=1` syntax.

For the evolver, which accepts a HybridSet as input, we instead need to write `x==1`.

I know that the latter is a special case of defining an interval, but shouldn't we be consistent?

Opinions @pietercollins ?

**Comment by pietercollins** [comment]
This is actually consistent; for a `Point`, we assign a single value to each variable, whereas for a `(Bounded)ConstraintSet`, we form a constraint, which restricts the value of an expression (here, the value of a variable is restricted to a singleton).
(There may be an inconsistency between `HybridPoint` and `Valuation`, though)

**Comment by lgeretti** [comment]
That's fine, though quite subtle from a user perspective.
