### ISSUE TITLE
Rounding a Real to Integer is very coarse

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#396]
I noticed that 

```
Integer round(Real const& r);
```

is very coarse. Namely, I tried with things such as `round(Real(0.2_dec)*100)` which yields 24. The Effort for this operation is hardcoded to 0. I tried using an effort equal to 1 and it yields 22, while with effort >=2 the result becomes 20.

Is there any reasonable effort strategy to follow, @pietercollins ?

**Comment by pietercollins** [comment]
Changed code to compute the dyaduc bounds using `Accuracy(2)`, which computes to an error at most +/-0.25. Rounding to the nearest dyadic to the midpoint will always return a number less than 1 from the argument.

The `Effort` argument seemed to be computing to a _relative_ error of 2^-e which is not guaranteed to give a neighbouring integer.
