### ISSUE TITLE
Redundant move statements in taylor_model.tpl.hpp

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#398]
Using g++-9.3.0 as shipped on Ubuntu 20.04, there are several redundant move statement warnings in taylor_model.tpl.hpp.

**Comment by pietercollins** [comment]
I only have g++-8.4 now, which doesn't give these warnings. But I checked all the std::move statements and it's ok to remove them, could you do this @lgeretti?

**Comment by lgeretti** [comment]
No problem.
