### ISSUE TITLE
Put the number of blocks in Kuhn reconditioning in the enclosure configuration

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#399]
The number of blocks is currently hard-coded, and from time to time I had to change it to better suit the examples I was working on. It's definitely worth putting it into the enclosure configuration.

**Comment by pietercollins** [comment]
Maybe even better: Make a `Reconditioner` or `Simplifier` class to perform the reconditioning.

**Comment by lgeretti** [comment]
Agreed

**Comment by lgeretti** [comment]
Moved the number of blocks in the enclosure configuration, for now.
