### ISSUE TITLE
LabelledBox class for convenience methods

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#407]
Operations such as extracting ranges for boxes held as LabelledSet<Box> is quite unwieldy: it's necessary to pass through the continuous set, extract the bounding box again, and access the proper dimension. It would be beneficial to handle boxes specifically.

**Comment by pietercollins** [comment]
Does the `VariablesBox` class do what you need? It's aimed at high-level use, while `LabelledSet<Box<I>>` is to allow access names for computed sets.

**Comment by lgeretti** [comment]
I believe it does. I recently enriched VectorFieldEvolver to allow conversion of RealVariablesBox into enclosure.

**Comment by lgeretti** [comment]
Would it be ok to return RealVariablesBox for the LabelledEnclosure::bounding_box() method?

**Comment by pietercollins** [comment]
Not really, `Labelled` sets should stay `Labelled`. 
So maybe a `LabelledBox` class inheriting from `LabelledSet<Box>` and providing subscripting.

**Comment by lgeretti** [comment]
That's what I was originally suggesting.

**Comment by lgeretti** [comment]
Done, supporting a single LabelledEnclosure and a ListSet<LabelledEnclosure>.
