### ISSUE TITLE
Segmentation fault on macOS g++, building with -O0 -O1

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#414]
I noticed an issue, reproducible only on macOS with g++ 9 and building with -O0 or -O1.
g++ 8 does not show the issue, neither does the Release configuration using -O3.

The testing code is the following:
```
    TaylorFunctionFactory factory = TaylorFunctionFactory(Sweeper<FloatDP>());

    ExactBoxType mydom({{0,1},{2,3},{4,5}});
    UpperBoxType mybx({{0,1},{2,3}});
    std::cout << factory.create_constants(mydom,cast_singleton(mybx)) << std::endl;
    std::cout << factory.create_constants(mydom,cast_singleton(mybx)) << std::endl;
    std::cout << "done." << std::endl;
```
which is a really very simple call made twice in a row. After the first call, the second one fails with a segfault.

**Comment by lgeretti** [comment]
By bisecting, this is the first bad commit: ee68cb45fcde7552e55dffc83a7ffe832c144fdc

**Comment by pietercollins** [comment]
At first glance, this seems like a memory (de)allocation error, maybe related to use of `Handle`.

**Comment by lgeretti** [comment]
You think? The bad commit does not seem to involve any use of `Handle`.

Unless you want to take a shot and try to understand the underlying issue in detail, I wouldn't work on this for the time being: the problem might be addressed in g++ 10. As soon as that toolchain is released on HomeBrew I will re-check this issue.

**Comment by pietercollins** [comment]
Is this Issue still unresolved?

**Comment by lgeretti** [comment]
I haven't checked more recently, but I wouldn't assume that the environment changed much. I'd hold it till the next major macOS release (Big Sur) in September/October.

**Comment by lgeretti** [comment]
By upgrading to g++ 10.2.0 this issue is solved, although I found a new one. Closing this.
