### ISSUE TITLE
Regression with storage plotting

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#419]
It seems that commit fa7ae6e2075f05f6d89b6d97bc1b7418b7fea6fe introduced a regression in plotting the grid set, as done in the hybrid_evolution_tutorial, which issues:

```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: std::runtime_error in symbolic/space.cpp:119: Ariadne::SizeType Ariadne::Space<Ariadne::Real>::index(const typename Space<T>::VariableType &) const [T = Ariadne::Real]: Assertion `false' failed.
  Variable aperture is not in the Space [height]
```

**Comment by pietercollins** [comment]
Fixed.
Updated (`Labelled`/`Hybrid`)`Storage` classes and related types to have a consistent relation to each other. The result is is little bit of a "class jungle" which would be nice to simplify if possible.
