### ISSUE TITLE
Change loop indices from Nat to SizeType

### ISSUE THREAD

**Issue by pietercollins** [ariadne-cps/ariadne#434]
We should consistently use `SizeType` (or `DimensionType` or `DegreeType` for loop indices, and not `Nat`. 
Note that the use of `Nat` should be reserved for builtin integers used in (real number) arithmetic, and not as counters/indices.

**Comment by lgeretti** [comment]
It shouldn't be too long a task, I don't believe there are many occurrences of `Nat` around anyway.
