### ISSUE TITLE
Split Number and Real classes into separate header files?

### ISSUE THREAD

**Issue by pietercollins** [ariadne-cps/ariadne#474]
Should we split the Number and Real classes into separate header files?  @lgeretti 

This would allow us to better target code to be `#include`d, at the cost of creating many more headers. Since we mostly just need Real and ValidatedNumber classes, splitting these off would save importing code which is mostly for specialised use cases.

**Comment by lgeretti** [comment]
If you believe this would improve things, I support the change.
In general I prefer having header files separated, since apart from navigational benefits they help us identify import boundaries.
