### ISSUE TITLE
Include local headers relative to top-level rather than to current file

### ISSUE THREAD

**Issue by pietercollins** [ariadne-cps/ariadne#483]
Could we include Ariadne header files relative to the top-level `source/` rather than the current file? 
This would mean changing e.g. `#include "../numeric/real.hpp"` to `#include "numeric/real.hpp"`. 
An advantage would be it's clearer to see the included file using `-H` or `-M` flags.

It works fine with local builds using `-iquote`, but I'm not sure if it also works if the files are installed in `/usr/local/include/`.
@lgeretti Do you know if this is ok?

**Comment by lgeretti** [comment]
I think there shouldn't be issues: I already did that for the configuration and concurrency modules successfully in my branch.

**Comment by lgeretti** [comment]
It's perfectly fine @pietercollins : see https://github.com/ariadne-cps/ariadne/pull/484 .
I can merge it if that's what you want.

**Comment by lgeretti** [comment]
Merged.
