### ISSUE TITLE
Enrich the simulator with the ability to follow multiple trajectories

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#569]
We shall enrich the simulator in order to get an idea of the behavior of a system when the initial set is large enough: instead of evolving from the midpoint, we should evolve from a list of points obtained by properly sampling the initial set.
There should be a configuration parameter that enables/disables this behavior.

**Comment by okrima** [comment]
Linked this issue with a brand new branch called "dynamics-simulator#569".
