### ISSUE TITLE
Gnuplot not working as optional

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#717]
It seems that, at least on macOS, not installing Gnuplot does still leak some references to Gnuplot classes that the compiler complains about.

**Comment by pietercollins** [comment]
I spotted this. One bug is in graphics manager, you should use `#elif defined(HAVE_GNUPLOT_H)` not `#elif HAVE_GNUPLOT_H` . There might be other issues.

**Comment by pietercollins** [comment]
Would it be possible to refactor the graphics to improve encapsulation. In principle, we should only need the `#if defined(...)` for the top-level headers and code files. We should also be able to remove the `#include "cairo.hpp"` and `#include "gnuplot.hpp"` in `command_line_interface.cpp` and `graphics_manager.cpp`.

The `GraphicsManager` class could have a `register_backend` method which can be called at startup from `cairo.cpp` or `gnuplot.cpp` to register that a backend is available. This information could be used by GraphicsBackendArgumentParser, including setting the `instructions` string. Once you have this, you can set the default backend by picking from the registered ones.

**Comment by pietercollins** [comment]
Also, the include guards in `graphics_submodule.cc` are mismatched with the code. 
Maybe there's some clever way of using metaprogramming to test if the backend exists when exporting, hence avoiding the preprocessor check.

**Comment by pietercollins** [comment]
Fixed include guards. Still recommend improving encapsulation of graphics.
