### ISSUE TITLE
Installation issues from the repository

### ISSUE THREAD

**Issue by pastankaitis** [ariadne-cps/ariadne#755]
Tried installing ariadne as suggested, but received the following issue and can't seem to progress. Any advice?

E: The repository 'https://ppa.launchpadcontent.net/ariadne-cps/ariadne/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by lgeretti** [comment]
Yes, there is no release at the moment for jammy, the supported version of Ubuntu is 20.04. We will address this, in the meantime you can install from sources any time.

**Comment by pastankaitis** [comment]
Many thanks, Luca. I think I managed to install from sources and was hoping to use your tool via Python, but can't get examples to work as it doesn't find pyrariadne module. Any suggestions?

**Comment by lgeretti** [comment]
What does the test suite do? Have you verified that CMake found everything as expected? I will need a clean log of the CMake setup output first. After the install, the pyariadne.so library should be installed in the proper directory.

**Comment by pastankaitis** [comment]
I just followed instructions your instructions, output from cmake --build . --target everything

[  2%] Built target ariadne-hybrid
[  2%] Built target CONCLOG_SRC
[  3%] Built target BETTERTHREADS_SRC
[  5%] Built target ariadne-utility
[ 11%] Built target ariadne-numeric
[ 13%] Built target ariadne-algebra
[ 18%] Built target ariadne-function
[ 22%] Built target ariadne-solvers
[ 26%] Built target ariadne-geometry
[ 30%] Built target ariadne-dynamics
[ 30%] Built target ariadne-symbolic
[ 32%] Built target ariadne-io
[ 32%] Built target ariadne
[ 32%] Building CXX object tutorials/demonstrations/CMakeFiles/solver_demonstration.dir/solver_demonstration.cpp.o
[ 32%] Linking CXX executable solver_demonstration
[ 32%] Built target solver_demonstration
[ 32%] Building CXX object tutorials/demonstrations/CMakeFiles/numeric_demonstration.dir/numeric_demonstration.cpp.o
[ 32%] Linking CXX executable numeric_demonstration
[ 32%] Built target numeric_demonstration
[ 32%] Building CXX object tutorials/demonstrations/CMakeFiles/algebra_demonstration.dir/algebra_demonstration.cpp.o
[ 32%] Linking CXX executable algebra_demonstration
[ 32%] Built target algebra_demonstration
[ 32%] Building CXX object tutorials/demonstrations/CMakeFiles/function_demonstration.dir/function_demonstration.cpp.o
[ 32%] Linking CXX executable function_demonstration
[ 32%] Built target function_demonstration
[ 33%] Building CXX object tutorials/demonstrations/CMakeFiles/geometry_demonstration.dir/geometry_demonstration.cpp.o
[ 33%] Linking CXX executable geometry_demonstration
[ 33%] Built target geometry_demonstration
[ 33%] Built target demonstrations
[ 35%] Building CXX object tutorials/CMakeFiles/rigorous_numerics_tutorial.dir/rigorous_numerics/rigorous_numerics_tutorial.cpp.o
[ 35%] Linking CXX executable rigorous_numerics_tutorial
[ 35%] Built target rigorous_numerics_tutorial
[ 35%] Building CXX object tutorials/CMakeFiles/hybrid_evolution_tutorial.dir/hybrid_evolution/hybrid_evolution_tutorial.cpp.o
[ 35%] Linking CXX executable hybrid_evolution_tutorial
[ 35%] Built target hybrid_evolution_tutorial
[ 35%] Built target tutorials
[ 35%] Built target test_hybrid_reachability
[ 35%] Built target ariadne-kernel
[ 35%] Built target test_array
[ 35%] Built target test_container
[ 36%] Built target test_lru_cache
[ 37%] Built target test_stopwatch
[ 37%] Built target test_stack_trace
[ 37%] Built target ariadne-core
[ 37%] Built target test_logical
[ 37%] Built target test_integer
[ 37%] Built target test_dyadic
[ 37%] Built target test_rational
[ 38%] Built target test_real
[ 38%] Built target test_number
[ 40%] Built target test_rounding_mode
[ 40%] Built target test_float
[ 41%] Built target test_float_rounding
[ 41%] Built target test_rounded_float
[ 42%] Built target test_float_approximation
[ 42%] Built target test_float_lower_upper_bound
[ 43%] Built target test_float_bounds
[ 43%] Built target test_float_ball
[ 45%] Built target test_complex
[ 46%] Built target test_differential
[ 47%] Built target test_algebra
[ 47%] Built target test_expansion
[ 48%] Built target test_graded
[ 48%] Built target test_matrix
[ 50%] Built target test_multi_index
[ 50%] Built target test_series
[ 50%] Built target test_vector
[ 51%] Built target test_function
[ 52%] Built target test_measurable_function
[ 52%] Built target test_multifunction
[ 52%] Built target test_polynomial
[ 52%] Built target test_chebyshev_polynomial
[ 52%] Built target test_formula
[ 53%] Built target test_procedure
[ 53%] Built target test_taylor_function
[ 55%] Built target test_taylor_model
[ 56%] Built target test_expression
[ 57%] Built target test_expression_set
[ 57%] Built target test_affine_sets
[ 58%] Built target test_binary_tree
[ 60%] Built target test_box
[ 61%] Built target test_point_curve
[ 61%] Built target test_constrained_image_set
[ 61%] Built target test_interval
[ 61%] Built target test_grid_paving
[ 62%] Built target test_paving
[ 62%] Built target test_measurable_set
[ 62%] Built target test_bounder
[ 63%] Built target test_constraint_solver
[ 65%] Built target test_integrator
[ 66%] Built target test_linear_programming
[ 67%] Built target test_nonlinear_programming
[ 68%] Built target test_solvers
[ 68%] Built target test_figure
[ 68%] Built target test_gnuplot
[ 68%] Built target test_command_line_interface
[ 70%] Built target test_enclosure
[ 71%] Built target test_iterated_map
[ 71%] Built target test_iterated_map_evolver
[ 72%] Built target test_vector_field
[ 72%] Built target test_vector_field_evolver
[ 73%] Built target test_vector_field_simulator
[ 73%] Built target test_differential_inclusion
[ 75%] Built target test_differential_inclusion_evolver
[ 76%] Built target test_finite_time_reachability
[ 77%] Built target test_infinite_time_reachability
[ 77%] Built target test_verify_safety
[ 77%] Built target test_pdes
[ 78%] Built target test_hybrid_automaton
[ 80%] Built target test_hybrid_evolution
[ 80%] Built target test_hybrid_evolver
[ 81%] Built target test_hybrid_graphics
[ 81%] Built target test_hybrid_enclosure
[ 82%] Built target test_hybrid_set
[ 82%] Built target test_hybrid_simulator
[ 82%] Built target tests
[ 83%] Building CXX object experimental/examples/hybrid/threewatertanks/CMakeFiles/threewatertanks.dir/threewatertanks.cpp.o
[ 83%] Linking CXX executable threewatertanks
[ 83%] Built target threewatertanks
[ 83%] Building CXX object examples/discrete/CMakeFiles/henon_map.dir/henon_map.cpp.o
[ 83%] Linking CXX executable henon_map
[ 83%] Built target henon_map
[ 83%] Building CXX object examples/continuous/CMakeFiles/attractor.dir/attractor.cpp.o
[ 83%] Linking CXX executable attractor
[ 83%] Built target attractor
[ 85%] Building CXX object examples/continuous/CMakeFiles/vanderpol.dir/vanderpol.cpp.o
[ 85%] Linking CXX executable vanderpol
[ 85%] Built target vanderpol
[ 86%] Building CXX object examples/continuous/noisy/CMakeFiles/higgins-selkov.dir/higgins-selkov.cpp.o
[ 86%] Linking CXX executable higgins-selkov
[ 86%] Built target higgins-selkov
[ 86%] Building CXX object examples/continuous/noisy/CMakeFiles/chemical-reactor.dir/chemical-reactor.cpp.o
[ 87%] Linking CXX executable chemical-reactor
[ 87%] Built target chemical-reactor
[ 88%] Building CXX object examples/continuous/noisy/CMakeFiles/lotka-volterra.dir/lotka-volterra.cpp.o
[ 88%] Linking CXX executable lotka-volterra
[ 88%] Built target lotka-volterra
[ 90%] Building CXX object examples/continuous/noisy/CMakeFiles/jet-engine.dir/jet-engine.cpp.o
[ 90%] Linking CXX executable jet-engine
[ 90%] Built target jet-engine
[ 90%] Building CXX object examples/continuous/noisy/CMakeFiles/pi-controller.dir/pi-controller.cpp.o
[ 90%] Linking CXX executable pi-controller
[ 90%] Built target pi-controller
[ 90%] Building CXX object examples/continuous/noisy/CMakeFiles/jerk21.dir/jerk21.cpp.o
[ 90%] Linking CXX executable jerk21
[ 90%] Built target jerk21
[ 90%] Building CXX object examples/continuous/noisy/CMakeFiles/lorenz-attractor.dir/lorenz-attractor.cpp.o
[ 90%] Linking CXX executable lorenz-attractor
[ 90%] Built target lorenz-attractor
[ 91%] Building CXX object examples/continuous/noisy/CMakeFiles/rossler-attractor.dir/rossler-attractor.cpp.o
[ 91%] Linking CXX executable rossler-attractor
[ 91%] Built target rossler-attractor
[ 92%] Building CXX object examples/continuous/noisy/CMakeFiles/jerk16.dir/jerk16.cpp.o
[ 92%] Linking CXX executable jerk16
[ 92%] Built target jerk16
[ 92%] Building CXX object examples/continuous/noisy/CMakeFiles/dc-dc.dir/dc-dc.cpp.o
[ 92%] Linking CXX executable dc-dc
[ 92%] Built target dc-dc
[ 93%] Building CXX object examples/continuous/noisy/CMakeFiles/noisy-benchmark.dir/noisy-benchmark.cpp.o
[ 93%] Linking CXX executable noisy-benchmark
[ 93%] Built target noisy-benchmark
[ 95%] Building CXX object examples/hybrid/CMakeFiles/bouncingball.dir/bouncingball.cpp.o
[ 95%] Linking CXX executable bouncingball
[ 95%] Built target bouncingball
[ 96%] Building CXX object examples/hybrid/CMakeFiles/heating.dir/heating.cpp.o
[ 96%] Linking CXX executable heating
[ 96%] Built target heating
[ 96%] Building CXX object examples/hybrid/CMakeFiles/rectifier.dir/rectifier.cpp.o
[ 96%] Linking CXX executable rectifier
[ 96%] Built target rectifier
[ 96%] Building CXX object examples/hybrid/watertank/CMakeFiles/watertank-hysteresis.dir/watertank-hysteresis.cpp.o
[ 96%] Linking CXX executable watertank-hysteresis
[ 96%] Built target watertank-hysteresis
[ 97%] Building CXX object examples/hybrid/watertank/CMakeFiles/watertank-proportional.dir/watertank-proportional.cpp.o
[ 97%] Linking CXX executable watertank-proportional
[ 97%] Built target watertank-proportional
[ 98%] Building CXX object examples/pdes/CMakeFiles/dirichlet.dir/dirichlet.cpp.o
[ 98%] Linking CXX executable dirichlet
[ 98%] Built target dirichlet
[ 98%] Building CXX object examples/pdes/CMakeFiles/acoustic_first_order_pde.dir/acoustic_first_order_pde.cpp.o
[100%] Linking CXX executable acoustic_first_order_pde
[100%] Built target acoustic_first_order_pde
[100%] Building CXX object experimental/examples/hybrid/twowatertanks/CMakeFiles/twowatertanks.dir/twowatertanks.cpp.o
[100%] Linking CXX executable twowatertanks
[100%] Built target twowatertanks
[100%] Built target examples
[100%] Built target everything

**Comment by lgeretti** [comment]
I need the results of the initial CMake configuration, so remove all files in the build/ directory and from there do 

cmake .. 

(plus any arguments that pertain to your installation, such as the compiler and the build type) copying the results here.

**Comment by pastankaitis** [comment]
It doesn't seem to find pytest package, though I have it. 

-- CMake version 3.26.4
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of char
-- Check size of char - done
-- Check size of short int
-- Check size of short int - done
-- Check size of int
-- Check size of int - done
-- Check size of long int
-- Check size of long int - done
-- Check size of long long int
-- Check size of long long int - done
-- Check size of float
-- Check size of float - done
-- Check size of double
-- Check size of double - done
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for execinfo.h
-- Looking for execinfo.h - found
-- Looking for C++ include cxxabi.h
-- Looking for C++ include cxxabi.h - found
-- Found Git: /usr/bin/git (found version "2.34.1") 
-- Getting all submodules if not downloaded already...
-- pybind11 submodule found
-- ConcLog submodule found
-- BetterThreads submodule found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found GMP: /usr/include/x86_64-linux-gnu (Required is at least version "5.1.0") 
-- Found MPFR: /usr/include (Required is at least version "1.0.0") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'cairo'
--   Found cairo, version 1.16.0
-- Found Cairo: /usr/lib/x86_64-linux-gnu/libcairo.so  
-- Found Gnuplot: /usr/bin/gnuplot (found suitable version "5.4.2", minimum required is "5.2.8") 
-- Check size of size_t
-- Check size of size_t - done
-- size_t size: 8
-- long int size: 8
-- long long int size: 8
-- Getting all submodules if not downloaded already...
-- ConcLog submodule found
-- Found Python3: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter Development Development.Module Development.Embed 
-- pybind11 v2.9.2 
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Please note that you need to use the Python 3 interpreter to import pyariadne correctly.
CMake Warning at python/tests/CMakeLists.txt:6 (message):
  pytest package not available, will not perform Python tests.


-- Configuring done (2.8s)
-- Generating done (0.4s)
-- Build files have been written to: /home/paulius/Software/ariadne/build

**Comment by lgeretti** [comment]
Never had this pytest package problem on Ubuntu, only on macOS (and it could only be solved by upgrading the macOS image). However, while not strictly necessary, if we want to check what's wrong with your pyariadne import it may be useful to make this work.

For the time being though, just do a full build and then copy-paste the results of the cmake install command, so I can see where pyariadne.so is installed.

**Comment by lgeretti** [comment]
Got it, all good there.
Does Python not find the pyariadne.so module or the libariadne.so lib?
In the latter case, you should just

export LD_LIBRARY_PATH=/usr/local/lib

In the former case, this may work:

export PYTHONPATH=/usr/lib/python3/dist-packages/

Luca

**Comment by pastankaitis** [comment]
I tried the latter PYTHONPATH and know getting the following when running one of the examples:

Traceback (most recent call last):
  File "/home/paulius/Software/ariadne/python/examples/continuous/attractor.py", line 24, in <module>
    from pyariadne import *
ImportError: /home/paulius/anaconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/python3/dist-packages/pyariadne.so)

**Comment by lgeretti** [comment]
It looks here you are not using the standard libstdc++ but rather one installed by you. And the corresponding glibcxx is not matching the version required by pyariadne. Can't you use the default standard library?

**Comment by pastankaitis** [comment]
Many thanks, Luca, I made some further changes. I just get the following error (from running attractor.py example), but this is probably to do with the code and I might figure it out.

Traceback (most recent call last):
  File "/home/paulius/Software/ariadne/python/examples/continuous/attractor.py", line 30, in <module>
    initial_set = RealExpressionBoundedConstraintSet([(dec(0.9)<=x)&(x<=1),(dec(-2.2)<=y)&(y<=-2)],[sqr(x)+sqr(y+2)<=1])
NameError: name 'dec' is not defined. Did you mean: 'dec_'?

**Comment by lgeretti** [comment]
The example apparently has not been updated. I will file an issue. Just refer to Python tutorials (which are tested in GitHub Actions so they must be correct) in case you are having problems with the examples. Closing this.
